//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;

namespace Primavera.Lithium.PythonConnector.Models.Metadata
{
    #region Code

    #region Public Classes

    /// <summary>
    /// Defines constants that specify the API versions used by the Web API actions.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public static partial class ApiVersions
    {
        #region Code

        #region Public Classes

        /// <summary>
        /// Defines constants that specify the API versions used by the Web API actions.
        /// </summary>
        [GeneratedCode("Lithium", "2.0")]
        public static partial class Literals
        {
            #region Code

            #region Public Constants

            /// <summary>
            /// The service default API version literal.
            /// </summary>
            public const string DefaultVersionLiteral = OneDotZeroLiteral;

            /// <summary>
            /// The 1.0 API version literal.
            /// </summary>
            public const string OneDotZeroLiteral = "1.0";

            #endregion

            #endregion
        }

        /// <summary>
        /// Defines constants that specify the API versions used by the Web API actions.
        /// </summary>
        [GeneratedCode("Lithium", "2.0")]
        public static partial class Values
        {
            #region Code

            #region Public Properties

            /// <summary>
            /// The service default API version.
            /// </summary>
            public static Version DefaultVersion
            {
                get
                {
                    return OneDotZero;
                }
            }

            /// <summary>
            /// The 1.0 API version.
            /// </summary>
            public static Version OneDotZero
            {
                get
                {
                    return new Version("1.0");
                }
            }

            #endregion

            #endregion
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
