//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

namespace Primavera.Lithium.PythonConnector.Models
{
    #region Code

    #region Public Classes

    /// <summary>
    /// Provides means to access resource strings.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class ModelsResources
    {
        #region Code

        #region Fields

        private static ResourceManager fieldResourceManager;
        private static CultureInfo fieldResourceCulture;

        #endregion

        #region Public Properties

        /// <summary>
        /// Gets the RES_Display_InputData_Date resource string.
        /// </summary>
        public static string RES_Display_InputData_Date
        {
            get
            {
                return ResourceManager.GetString("RES_Display_InputData_Date", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_InputData_Key resource string.
        /// </summary>
        public static string RES_Display_InputData_Key
        {
            get
            {
                return ResourceManager.GetString("RES_Display_InputData_Key", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_InputData_Value resource string.
        /// </summary>
        public static string RES_Display_InputData_Value
        {
            get
            {
                return ResourceManager.GetString("RES_Display_InputData_Value", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_AnomalyScore resource string.
        /// </summary>
        public static string RES_Display_OutputData_AnomalyScore
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_AnomalyScore", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_AnomalyType resource string.
        /// </summary>
        public static string RES_Display_OutputData_AnomalyType
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_AnomalyType", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_ConfidenceLevel resource string.
        /// </summary>
        public static string RES_Display_OutputData_ConfidenceLevel
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_ConfidenceLevel", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_Correlations resource string.
        /// </summary>
        public static string RES_Display_OutputData_Correlations
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_Correlations", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_DispersionScore resource string.
        /// </summary>
        public static string RES_Display_OutputData_DispersionScore
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_DispersionScore", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_EndTime resource string.
        /// </summary>
        public static string RES_Display_OutputData_EndTime
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_EndTime", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_GlobalIntensity resource string.
        /// </summary>
        public static string RES_Display_OutputData_GlobalIntensity
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_GlobalIntensity", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_Key resource string.
        /// </summary>
        public static string RES_Display_OutputData_Key
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_Key", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_MovingIntensity resource string.
        /// </summary>
        public static string RES_Display_OutputData_MovingIntensity
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_MovingIntensity", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_Polarity resource string.
        /// </summary>
        public static string RES_Display_OutputData_Polarity
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_Polarity", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_StartTime resource string.
        /// </summary>
        public static string RES_Display_OutputData_StartTime
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_StartTime", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_OutputData_WeightedMovingIntensity resource string.
        /// </summary>
        public static string RES_Display_OutputData_WeightedMovingIntensity
        {
            get
            {
                return ResourceManager.GetString("RES_Display_OutputData_WeightedMovingIntensity", Culture);
            }
        }

        #endregion

        #region Internal Properties

        /// <summary>
        /// Gets the resource manager.
        /// </summary>
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (fieldResourceManager == null)
                {
                    fieldResourceManager = new ResourceManager("Primavera.Lithium.PythonConnector.Models.GeneratedCode.ModelsResources.gen", typeof(ModelsResources).Assembly);
                }
                
                return fieldResourceManager;
            }
        }

        /// <summary>
        /// Gets or sets the culture.
        /// </summary>
        internal static CultureInfo Culture
        {
            get
            {
                return fieldResourceCulture;
            }
            set
            {
                fieldResourceCulture = value;
            }
        }

        #endregion

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsResources"/> class.
        /// </summary>
        public ModelsResources()        
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
