//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace Primavera.Lithium.PythonConnector.Models
{
    #region Code

    #region Public Classes

    /// <summary>
    /// Defines the base class for <see cref="InputData"/>.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public abstract partial class InputDataBase
    {
        #region Code

        #region Public Properties

        /// <summary>
        /// Input data date.
        /// </summary>
        [Primavera.Hydrogen.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_InputData_Date), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("date")]
        public virtual string Date
        {
            get;
            set;
        }

        /// <summary>
        /// Input data key.
        /// </summary>
        [Primavera.Hydrogen.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_InputData_Key), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("key")]
        public virtual string Key
        {
            get;
            set;
        }

        /// <summary>
        /// Input data value.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_InputData_Value), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public virtual double Value
        {
            get;
            set;
        }

        #endregion

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="InputDataBase"/> class.
        /// </summary>
        protected InputDataBase()        
        {
            // Initialize default values

            this.SetDefaultValues();
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Sets the default values.
        /// </summary>
        /// <remarks>
        /// This method should be overridden to set the default values of properties.
        /// </remarks>
        protected virtual void SetDefaultValues()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// The input data.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class InputData : InputDataBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="InputData"/> class.
        /// </summary>
        public InputData()        
            : base()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Defines the base class for <see cref="OutputData"/>.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public abstract partial class OutputDataBase
    {
        #region Code

        #region Public Properties

        /// <summary>
        /// Output data anomaly score.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_AnomalyScore), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("anomalyScore")]
        public virtual double AnomalyScore
        {
            get;
            set;
        }

        /// <summary>
        /// Output data anomaly type.
        /// </summary>
        [Primavera.Hydrogen.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_AnomalyType), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("anomalyType")]
        public virtual string AnomalyType
        {
            get;
            set;
        }

        /// <summary>
        /// Output data confidence level.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_ConfidenceLevel), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("confidenceLevel")]
        public virtual double ConfidenceLevel
        {
            get;
            set;
        }

        /// <summary>
        /// Output data correlations.
        /// </summary>
        [Primavera.Hydrogen.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_Correlations), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("correlations")]
        public virtual string Correlations
        {
            get;
            set;
        }

        /// <summary>
        /// Output data dispersion score.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_DispersionScore), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("dispersionScore")]
        public virtual double DispersionScore
        {
            get;
            set;
        }

        /// <summary>
        /// Output data end time.
        /// </summary>
        [Primavera.Hydrogen.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_EndTime), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("endTime")]
        public virtual string EndTime
        {
            get;
            set;
        }

        /// <summary>
        /// Output data global intensity.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_GlobalIntensity), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("globalIntensity")]
        public virtual double GlobalIntensity
        {
            get;
            set;
        }

        /// <summary>
        /// Output data key.
        /// </summary>
        [Primavera.Hydrogen.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_Key), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("key")]
        public virtual string Key
        {
            get;
            set;
        }

        /// <summary>
        /// Output data moving intensity.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_MovingIntensity), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("movingIntensity")]
        public virtual double MovingIntensity
        {
            get;
            set;
        }

        /// <summary>
        /// Output data polarity.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_Polarity), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("polarity")]
        public virtual double Polarity
        {
            get;
            set;
        }

        /// <summary>
        /// Output data start time.
        /// </summary>
        [Primavera.Hydrogen.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = false)]
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_StartTime), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("startTime")]
        public virtual string StartTime
        {
            get;
            set;
        }

        /// <summary>
        /// Output data weighted moving intensity.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Display(Name = nameof(ModelsResources.RES_Display_OutputData_WeightedMovingIntensity), ResourceType = typeof(ModelsResources))]
        [System.Text.Json.Serialization.JsonPropertyName("weightedMovingIntensity")]
        public virtual double WeightedMovingIntensity
        {
            get;
            set;
        }

        #endregion

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="OutputDataBase"/> class.
        /// </summary>
        protected OutputDataBase()        
        {
            // Initialize default values

            this.SetDefaultValues();
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Sets the default values.
        /// </summary>
        /// <remarks>
        /// This method should be overridden to set the default values of properties.
        /// </remarks>
        protected virtual void SetDefaultValues()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// The output data.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class OutputData : OutputDataBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="OutputData"/> class.
        /// </summary>
        public OutputData()        
            : base()
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
