//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Primavera.Hydrogen;
using Primavera.Hydrogen.Rest.Routing;

namespace Primavera.Lithium.PythonConnector.Models.Metadata
{
    #region Code

    #region Public Classes

    /// <summary>
    /// Defines the base class for a class that defines constants that specify the routes used by the Web API actions.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public abstract partial class RoutesBase
    {
        #region Code

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="RoutesBase"/> class.
        /// </summary>
        protected RoutesBase()        
        {
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Returns the full URI to access the specified route when the service is hosted in a given base URI.
        /// </summary>
        /// <param name="baseUri">The base URI of the service.</param>
        /// <param name="route">The route (as defined in <see cref="Routes" />).</param>
        /// <param name="properties">The objects that should be formatted. The key of the dictionary specifies the property name.</param>
        /// <returns>
        /// The full URI to access the specified route.
        /// </returns>
        public virtual Uri Resolve(Uri baseUri, string route, IReadOnlyDictionary<string, object> properties)
        {
            // Validation

            SmartGuard.NotNullOrEmpty(() => properties, properties);

            // Result

            return new Uri(
                UriHelper.Combine(
                    baseUri.AbsoluteUri,
                    RouteTemplateResolver.Resolve(
                        route,
                        properties)));
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Defines constants that specify the routes used by the Web API actions.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public sealed partial class Routes : RoutesBase
    {
        #region Code

        #region Public Classes

        /// <summary>
        /// Defines constants that specify the routes used by the monitoring actions.
        /// </summary>
        [GeneratedCode("Lithium", "2.0")]
        public static partial class Monitoring
        {
            #region Code

            #region Public Constants

            /// <summary>
            /// Defines the route for the action that probes the service. This action is used to perform dependencies tests on the service.
            /// </summary>
            public const string Probe = "api/v{version:apiVersion}/monitoring/probe";

            /// <summary>
            /// Defines the route for the action that diagnoses the service. This action is used to perform functional tests on the service.
            /// </summary>
            public const string Diagnostics = "api/v{version:apiVersion}/monitoring/diagnostics";

            /// <summary>
            /// Defines the route for the action that analyzes the endpoints of the service. This action is used to verify the service implementation.
            /// </summary>
            public const string Endpoints = "api/v{version:apiVersion}/monitoring/endpoints";

            /// <summary>
            /// Defines the route for the action that analyzes the configuration of the service. This action is used to verify the service implementation.
            /// </summary>
            public const string Configuration = "api/v{version:apiVersion}/monitoring/configuration";

            #endregion

            #endregion
        }

        /// <summary>
        /// Defines constants that specify the routes used by the python connector actions.
        /// </summary>
        [GeneratedCode("Lithium", "2.0")]
        public static partial class PythonConnector
        {
            #region Code

            #region Public Constants

            /// <summary>
            /// Defines the route for the following action: Get Result.
            /// </summary>
            public const string GetResult = "/api/v{version:apiVersion}/pythonconnector";

            #endregion

            #endregion
        }

        #endregion

        #region Fields

        private static Routes fieldInstance;

        #endregion

        #region Public Properties

        /// <summary>
        /// Gets the instance
        /// </summary>
        public static Routes Instance
        {
            get
            {
                if (fieldInstance == null)
                {
                    fieldInstance = new Routes();
                }

                return fieldInstance;
            }
        }

        #endregion

        #region Private Constructors

        private Routes()        
            : base()
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
