//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Logging;
using Primavera.Hydrogen.AspNetCore.Hosting;

namespace Primavera.Lithium.PythonConnector.WebApi.BackgroundServices
{
    #region Code

    #endregion
}
