//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Primavera.Lithium.PythonConnector.WebApi.Controllers
{
    #region Code

    #region Internal Classes

    /// <summary>
    /// Provides the error codes that can be returned by the Web API.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    internal static partial class ErrorCodes
    {
        #region Code

        #region Internal Constants

        /// <summary>
        /// The request arguments are invalid.
        /// </summary>
        internal const string RequestArgsInvalid = "RequestArgsInvalid";

        /// <summary>
        /// InputData is required.
        /// </summary>
        internal const string PythonConnectorGetResultInputDataRequired = "InputDataRequired";

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
