//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Primavera.Hydrogen.Rest.Routing;

namespace Primavera.Lithium.PythonConnector.WebApi.Controllers
{
    #region Code

    #region Public Interfaces

    /// <summary>
    /// Defines the interface of the controller that provides monitoring routes.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial interface IMonitoringController
    {
        #region Code

        #region Methods

        /// <summary>
        /// Provides an action that probes the service. This action is used to perform dependencies tests on the service.
        /// </summary>
        /// <returns>
        /// OK.
        /// </returns>
        Task<IActionResult> ProbeAsync();

        /// <summary>
        /// Provides an action that diagnoses the service. This action is used to perform functional tests on the service.
        /// </summary>
        /// <returns>
        /// OK.
        /// </returns>
        Task<IActionResult> DiagnosticsAsync();

        /// <summary>
        /// Provides an action that analyzes the endpoints of the service. This action is used to verify the service implementation.
        /// </summary>
        /// <returns>
        /// The list containing the endpoints.
        /// </returns>
        Task<IActionResult> EndpointsAsync();

        /// <summary>
        /// Provides an action that analyzes the configuration of the service. This action is used to verify the service implementation.
        /// </summary>
        /// <returns>
        /// OK.
        /// </returns>
        /// <remarks>
        /// If the service uses blob storage, the configuration options will be dumped in a blob container named 'ConfigAnalyzer'. Otherwise, the configuration options will be saved in a file named 'ConfigAnalyzer.json'.
        /// </remarks>
        Task<IActionResult> ConfigurationAsync();

        #endregion

        #endregion
    }

    /// <summary>
    /// The python connector controller.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial interface IPythonConnectorController
    {
        #region Code

        #region Methods

        /// <summary>
        /// The python connector get result.
        /// </summary>
        /// <param name="inputData">The input data.</param>
        /// <returns>
        /// Returns the output data.
        /// </returns>
        Task<IActionResult> GetResultAsync(IEnumerable<Primavera.Lithium.PythonConnector.Models.InputData> inputData);

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
