//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

namespace Primavera.Lithium.PythonConnector.WebApi.Controllers
{
    #region Code

    #region Public Classes

    /// <summary>
    /// Provides means to access resource strings.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class ViewsResources
    {
        #region Code

        #region Fields

        private static ResourceManager fieldResourceManager;
        private static CultureInfo fieldResourceCulture;

        #endregion

        #region Public Properties

        /// <summary>
        /// Gets the RES_PageTitle_Error resource string.
        /// </summary>
        public static string RES_PageTitle_Error
        {
            get
            {
                return ResourceManager.GetString("RES_PageTitle_Error", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_PageTitle_Error_StatusCode resource string.
        /// </summary>
        public static string RES_PageTitle_Error_StatusCode
        {
            get
            {
                return ResourceManager.GetString("RES_PageTitle_Error_StatusCode", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Title_Error resource string.
        /// </summary>
        public static string RES_Title_Error
        {
            get
            {
                return ResourceManager.GetString("RES_Title_Error", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Title_403 resource string.
        /// </summary>
        public static string RES_Title_403
        {
            get
            {
                return ResourceManager.GetString("RES_Title_403", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Title_404 resource string.
        /// </summary>
        public static string RES_Title_404
        {
            get
            {
                return ResourceManager.GetString("RES_Title_404", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Title_500 resource string.
        /// </summary>
        public static string RES_Title_500
        {
            get
            {
                return ResourceManager.GetString("RES_Title_500", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Title_StatusCode resource string.
        /// </summary>
        public static string RES_Title_StatusCode
        {
            get
            {
                return ResourceManager.GetString("RES_Title_StatusCode", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Description_Unexpected resource string.
        /// </summary>
        public static string RES_Description_Unexpected
        {
            get
            {
                return ResourceManager.GetString("RES_Description_Unexpected", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Description_403 resource string.
        /// </summary>
        public static string RES_Description_403
        {
            get
            {
                return ResourceManager.GetString("RES_Description_403", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Description_404 resource string.
        /// </summary>
        public static string RES_Description_404
        {
            get
            {
                return ResourceManager.GetString("RES_Description_404", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Description_500 resource string.
        /// </summary>
        public static string RES_Description_500
        {
            get
            {
                return ResourceManager.GetString("RES_Description_500", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Description_StatusCode resource string.
        /// </summary>
        public static string RES_Description_StatusCode
        {
            get
            {
                return ResourceManager.GetString("RES_Description_StatusCode", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Description_Unexpected_ErrorId resource string.
        /// </summary>
        public static string RES_Description_Unexpected_ErrorId
        {
            get
            {
                return ResourceManager.GetString("RES_Description_Unexpected_ErrorId", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_ErrorId resource string.
        /// </summary>
        public static string RES_ErrorId
        {
            get
            {
                return ResourceManager.GetString("RES_ErrorId", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_SignedInAs resource string.
        /// </summary>
        public static string RES_SignedInAs
        {
            get
            {
                return ResourceManager.GetString("RES_SignedInAs", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_NoFeaturesForWebBrowsers resource string.
        /// </summary>
        public static string RES_NoFeaturesForWebBrowsers
        {
            get
            {
                return ResourceManager.GetString("RES_NoFeaturesForWebBrowsers", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_ClientLibraryDocumentation resource string.
        /// </summary>
        public static string RES_ClientLibraryDocumentation
        {
            get
            {
                return ResourceManager.GetString("RES_ClientLibraryDocumentation", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_WebApiDocumentation resource string.
        /// </summary>
        public static string RES_WebApiDocumentation
        {
            get
            {
                return ResourceManager.GetString("RES_WebApiDocumentation", Culture);
            }
        }

        #endregion

        #region Internal Properties

        /// <summary>
        /// Gets the resource manager.
        /// </summary>
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (fieldResourceManager == null)
                {
                    fieldResourceManager = new ResourceManager("Primavera.Lithium.PythonConnector.WebApi.GeneratedCode.ViewsResources.gen", typeof(ViewsResources).Assembly);
                }
                
                return fieldResourceManager;
            }
        }

        /// <summary>
        /// Gets or sets the culture.
        /// </summary>
        internal static CultureInfo Culture
        {
            get
            {
                return fieldResourceCulture;
            }
            set
            {
                fieldResourceCulture = value;
            }
        }

        #endregion

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewsResources"/> class.
        /// </summary>
        public ViewsResources()        
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
