//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

namespace Primavera.Lithium.PythonConnector.WebApi.Controllers
{
    #region Code

    #region Public Classes

    /// <summary>
    /// Provides means to access resource strings.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class WebhooksResources
    {
        #region Code

        #region Fields

        private static ResourceManager fieldResourceManager;
        private static CultureInfo fieldResourceCulture;

        #endregion

        #region Internal Properties

        /// <summary>
        /// Gets the resource manager.
        /// </summary>
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (fieldResourceManager == null)
                {
                    fieldResourceManager = new ResourceManager("Primavera.Lithium.PythonConnector.WebApi.GeneratedCode.WebhooksResources.gen", typeof(WebhooksResources).Assembly);
                }
                
                return fieldResourceManager;
            }
        }

        /// <summary>
        /// Gets or sets the culture.
        /// </summary>
        internal static CultureInfo Culture
        {
            get
            {
                return fieldResourceCulture;
            }
            set
            {
                fieldResourceCulture = value;
            }
        }

        #endregion

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksResources"/> class.
        /// </summary>
        public WebhooksResources()        
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
