//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using Primavera.Hydrogen;
using Primavera.Hydrogen.Rest.Client;
using Primavera.Hydrogen.Rest.Routing;

namespace Primavera.Lithium.PythonConnector
{
    #region Code

    #region Public Classes

    /// <summary>
    /// Defines the base class for the type that provides monitoring operations on the service.
    /// </summary>
    /// <seealso cref="IMonitoringOperations" />
    /// <seealso cref="IDisposable" />
    [GeneratedCode("Lithium", "2.0")]
    [SuppressMessage("Maintainability Rules", "SA1402:FileMayOnlyContainASingleType", Justification = "Because of code generation design.")]
    public abstract partial class MonitoringOperationsBase : IMonitoringOperations, IDisposable
    {
        #region Code

        #region Protected Properties

        /// <summary>
        /// Gets or sets the service client.
        /// </summary>
        protected virtual PythonConnectorClientBase Client
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the service client actions.
        /// </summary>
        protected virtual ServiceClientActions<PythonConnectorClientBase> Actions
        {
            get;
            set;
        }

        #endregion

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="MonitoringOperationsBase" /> class.
        /// </summary>
        /// <param name="client">The service client.</param>
        /// <param name="actions">The service client actions.</param>
        protected MonitoringOperationsBase(PythonConnectorClientBase client, ServiceClientActions<PythonConnectorClientBase> actions)        
        {
            // Validation

            SmartGuard.NotNull(() => client, client);
            SmartGuard.NotNull(() => actions, actions);

            // Set properties

            this.Client = client;
            this.Actions = actions;

            // Additional initialization

            this.Initialize();
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
        /// </summary>
        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }

        /// <inheritdoc />
        public virtual Task<ServiceOperationResult<string>> ProbeAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            // Build the URL of the request
            
            Uri requestUri = Models.Metadata.Routes.Instance.Resolve(
                this.Client.BaseUri,
                Models.Metadata.Routes.Monitoring.Probe, 
                new Dictionary<string, object>()
                {
                    ["version"] = this.Client.ApiVersion
                });
            
            // Result
            
            return this.Actions.ExecuteGetAsync<string>(requestUri, HttpStatusCode.OK, cancellationToken);
        }

        /// <inheritdoc />
        public virtual Task<ServiceOperationResult<string>> DiagnosticsAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            // Build the URL of the request
            
            Uri requestUri = Models.Metadata.Routes.Instance.Resolve(
                this.Client.BaseUri,
                Models.Metadata.Routes.Monitoring.Diagnostics, 
                new Dictionary<string, object>()
                {
                    ["version"] = this.Client.ApiVersion
                });
            
            // Result
            
            return this.Actions.ExecuteGetAsync<string>(requestUri, HttpStatusCode.OK, cancellationToken);
        }

        /// <inheritdoc />
        public virtual Task<ServiceOperationResult<IEnumerable<EndpointInfo>>> EndpointsAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            // Build the URL of the request
            
            Uri requestUri = Models.Metadata.Routes.Instance.Resolve(
                this.Client.BaseUri,
                Models.Metadata.Routes.Monitoring.Endpoints, 
                new Dictionary<string, object>()
                {
                    ["version"] = this.Client.ApiVersion
                });
            
            // Result
            
            return this.Actions.ExecuteGetAsync<IEnumerable<EndpointInfo>>(requestUri, HttpStatusCode.OK, cancellationToken);
        }

        /// <inheritdoc />
        public virtual Task<ServiceOperationResult<string>> ConfigurationAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            // Build the URL of the request
            
            Uri requestUri = Models.Metadata.Routes.Instance.Resolve(
                this.Client.BaseUri,
                Models.Metadata.Routes.Monitoring.Configuration, 
                new Dictionary<string, object>()
                {
                    ["version"] = this.Client.ApiVersion
                });
            
            // Result
            
            return this.Actions.ExecuteGetAsync<string>(requestUri, HttpStatusCode.OK, cancellationToken);
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Releases unmanaged and - optionally - managed resources.
        /// </summary>
        /// <param name="disposing"><c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
        protected virtual void Dispose(bool disposing)
        {
        }

        /// <summary>
        /// Performs additional initialization.
        /// </summary>
        protected virtual void Initialize()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Provides monitoring operations on the service.
    /// </summary>
    /// <seealso cref="MonitoringOperationsBase" />
    [GeneratedCode("Lithium", "2.0")]
    [SuppressMessage("Maintainability Rules", "SA1402:FileMayOnlyContainASingleType", Justification = "Because of code generation design.")]
    public partial class MonitoringOperations : MonitoringOperationsBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="MonitoringOperations" /> class.
        /// </summary>
        /// <param name="client">The service client.</param>
        /// <param name="actions">The service client actions.</param>
        public MonitoringOperations(PythonConnectorClientBase client, ServiceClientActions<PythonConnectorClientBase> actions)        
            : base(client, actions)
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// The python connector controller.
    /// </summary>
    /// <seealso cref="IPythonConnectorOperations" />
    /// <seealso cref="IDisposable" />
    [GeneratedCode("Lithium", "2.0")]
    [SuppressMessage("Maintainability Rules", "SA1402:FileMayOnlyContainASingleType", Justification = "Because of code generation design.")]
    public abstract partial class PythonConnectorOperationsBase : IPythonConnectorOperations, IDisposable
    {
        #region Code

        #region Protected Properties

        /// <summary>
        /// Gets or sets the service client.
        /// </summary>
        protected virtual PythonConnectorClientBase Client
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the service client actions.
        /// </summary>
        protected virtual ServiceClientActions<PythonConnectorClientBase> Actions
        {
            get;
            set;
        }

        #endregion

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="PythonConnectorOperationsBase" /> class.
        /// </summary>
        /// <param name="client">The service client.</param>
        /// <param name="actions">The service client actions.</param>
        protected PythonConnectorOperationsBase(PythonConnectorClientBase client, ServiceClientActions<PythonConnectorClientBase> actions)        
        {
            // Validation

            SmartGuard.NotNull(() => client, client);
            SmartGuard.NotNull(() => actions, actions);

            // Set properties

            this.Client = client;
            this.Actions = actions;

            // Additional initialization

            this.Initialize();
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
        /// </summary>
        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }

        /// <inheritdoc />
        public virtual Task<ServiceOperationResult<IEnumerable<Primavera.Lithium.PythonConnector.Models.OutputData>>> GetResultAsync(IEnumerable<Primavera.Lithium.PythonConnector.Models.InputData> inputData, CancellationToken cancellationToken = default(CancellationToken))
        {
            // Begin Validation

            SmartGuard.NotNull(() => inputData, inputData);
            SmartGuard.IsValid(() => inputData, inputData, 10, true);

            // End Validation

            // Route

            Uri requestUri = Models.Metadata.Routes.Instance.Resolve(
                this.Client.BaseUri,
                Models.Metadata.Routes.PythonConnector.GetResult,
                new Dictionary<string, object>()
                {
                    ["version"] = this.Client.ApiVersion
                });

            // Result

            return this.Actions.ExecutePostAsync<IEnumerable<Primavera.Lithium.PythonConnector.Models.InputData>, IEnumerable<Primavera.Lithium.PythonConnector.Models.OutputData>>(requestUri, inputData, HttpStatusCode.OK, cancellationToken);
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Releases unmanaged and - optionally - managed resources.
        /// </summary>
        /// <param name="disposing"><c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
        protected virtual void Dispose(bool disposing)
        {
        }

        /// <summary>
        /// Performs additional initialization.
        /// </summary>
        protected virtual void Initialize()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// The python connector controller.
    /// </summary>
    /// <seealso cref="PythonConnectorOperationsBase" />
    [GeneratedCode("Lithium", "2.0")]
    [SuppressMessage("Maintainability Rules", "SA1402:FileMayOnlyContainASingleType", Justification = "Because of code generation design.")]
    public partial class PythonConnectorOperations : PythonConnectorOperationsBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="PythonConnectorOperations" /> class.
        /// </summary>
        /// <param name="client">The service client.</param>
        /// <param name="actions">The service client actions.</param>
        public PythonConnectorOperations(PythonConnectorClientBase client, ServiceClientActions<PythonConnectorClientBase> actions)        
            : base(client, actions)
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
