//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;

namespace Primavera.Lithium.PythonConnector
{
    #region Code

    #region Public Interfaces

    /// <summary>
    /// Defines the interface of the service client that allows accessing the Python Connector Service Web API.
    /// </summary>
    /// <seealso cref="IDisposable" />
    [GeneratedCode("Lithium", "2.0")]
    public partial interface IPythonConnectorClient : IDisposable
    {
        #region Code

        #region Properties

        /// <summary>
        /// Provides monitoring operations on the service.
        /// </summary>
        IMonitoringOperations Monitoring
        {
            get;
        }

        /// <summary>
        /// The python connector controller.
        /// </summary>
        IPythonConnectorOperations PythonConnector
        {
            get;
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
