//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using Primavera.Hydrogen;
using Primavera.Hydrogen.Hosting;
using Primavera.Hydrogen.Rest;
using Primavera.Hydrogen.Rest.Client;
using Primavera.Hydrogen.Rest.Client.Authentication;
using Primavera.Hydrogen.Rest.Routing;
using Primavera.Lithium.PythonConnector.Client.Console.Configuration;

namespace Primavera.Lithium.PythonConnector.Client.Console
{
    #region Code

    #region Internal Classes

    /// <summary>
    /// Defines the base class for the type that implements the application.
    /// </summary>
    /// <seealso cref="IConsoleInteractiveApplication" />
    [GeneratedCode("Lithium", "2.0")]
    [SuppressMessage("Maintainability Rules", "SA1402:FileMayOnlyContainASingleType", Justification = "Because of code generation design.")]
    [SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Justification = "Created via dependency injection.")]
    internal abstract partial class ApplicationBase : IConsoleInteractiveApplication, IDisposable
    {
        #region Code

        #region Fields

        private PythonConnectorClient fieldClient;

        #endregion

        #region Protected Properties

        /// <summary>
        /// Gets the configuration.
        /// </summary>
        protected ApplicationConfiguration Configuration
        {
            get;
        }

        /// <summary>
        /// Gets the service client.
        /// </summary>
        protected virtual PythonConnectorClient Client
        {
            get
            {
                if (this.fieldClient == null)
                {
                    this.fieldClient = this.GetServiceClient();
                }

                return this.fieldClient;
            }
        }

        #endregion

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationBase"/> class.
        /// </summary>
        /// <param name="options">The application configuration options.</param>
        public ApplicationBase(ApplicationConfiguration options)        
        {
            // Validation

            SmartGuard.NotNull(() => options, options);

            // Set properties

            this.Configuration = options;

            // Set encoding

            System.Console.OutputEncoding = System.Text.Encoding.UTF8;
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Runs the application.
        /// </summary>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns>
        /// The <see cref="Task"/> that represents the asynchronous operation.
        /// </returns>
        /// <remarks>
        /// Override this method to implement the client application logic.
        /// </remarks>
        public async Task RunAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            // Heading

            ConsoleHelper.WriteLine("=======================================");
            ConsoleHelper.WriteLine("PYTHON CONNECTOR SERVICE CONSOLE");
            ConsoleHelper.WriteLine("=======================================");

            // Check configuration

            if (!this.CheckConfiguration())
            {
                return;
            }

            // Select environment

            this.SelectEnvironment();

            // Write configuration

            this.WriteConfiguration();
            
            // Menu

            bool cont = true;
            while (cont)
            {
                ConsoleHelper.WriteLine();
                ConsoleHelper.WriteLine("========================================");
                ConsoleHelper.WriteLine("Main Menu");
                this.WriteConfiguration();
                ConsoleHelper.WriteLine();
                ConsoleHelper.WriteLine("0. Change Environment.");

                this.PrintCustomMenuOptions();

                ConsoleHelper.WriteLine("M. Monitoring.");
                ConsoleHelper.WriteLine("Q. Quit.");
                ConsoleHelper.Write(">> ");

                ConsoleKeyInfo key = ConsoleHelper.ReadKey();
                ConsoleHelper.WriteLine();

                switch (key.Key)
                {
                    case ConsoleKey.Q:
                        cont = false;
                        break;
                    case ConsoleKey.D0:
                    case ConsoleKey.NumPad0:
                        this.SelectEnvironment();
                        cont = true;
                        break;
                    case ConsoleKey.M:
                        cont = !await this.ShowMonitoringMenuAsync().ConfigureAwait(false);
                        break;
                    default:
                        cont = await this.HandleCustomMenuOptionsAsync(key).ConfigureAwait(false);
                        break;
                }
            }
        }

        /// <summary>
        /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
        /// </summary>
        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Creates an instance of the service client.
        /// </summary>
        /// <returns>
        /// The <see cref="PythonConnectorClient"/> instance.
        /// </returns>
        protected virtual PythonConnectorClient GetServiceClient()
        {
            ConsoleHelper.WriteInformationLine("Creating the service client for base URI '{0}'...", this.Configuration.ServiceBaseUri);

            return new PythonConnectorClient(
                new Uri(this.Configuration.ServiceBaseUri),
                ServiceClientCredentials.NoCredentials);
        }

        /// <summary>
        /// Initializes the service client instance.
        /// </summary>
        /// <param name="client">The service client instance.</param>
        protected virtual void InitializeServiceClient(PythonConnectorClient client)
        {
        }

        /// <summary>
        /// Releases unmanaged and - optionally - managed resources.
        /// </summary>
        /// <param name="disposing"><c>True</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
        protected virtual void Dispose(bool disposing)
        {
            // Disposing?

            if (disposing)
            {
                this.DisposeServiceClient();
            }
        }

        /// <summary>
        /// Releases the service client.
        /// </summary>
        protected virtual void DisposeServiceClient()
        {
            if (this.fieldClient != null)
            {
                this.fieldClient.Dispose();
                this.fieldClient = null;
            }
        }

        /// <summary>
        /// Prints the custom menu options.
        /// </summary>
        /// <remarks>
        /// This method needs to be overridden to build the application menu.
        /// </remarks>
        protected abstract void PrintCustomMenuOptions();

        /// <summary>
        /// Handles the custom menu options.
        /// </summary>
        /// <param name="key">The key pressed by the user.</param>
        /// <returns>
        /// The <see cref="Task{TResult}"/> that represents the asynchronous operation.
        /// A value indicating whether the application should continue execution.
        /// </returns>
        /// <remarks>
        /// This method needs to be overridden to handle the custom application menu options.
        /// </remarks>
        protected abstract Task<bool> HandleCustomMenuOptionsAsync(ConsoleKeyInfo key);

        /// <summary>
        /// Writes the specified endpoints to the console.
        /// </summary>
        /// <param name="endpoints">The endpoints.</param>
        protected virtual void WriteEndpoints(IEnumerable<EndpointInfo> endpoints)
        {
            ConsoleHelper.WriteInformationLine("Endpoints:");

            if (endpoints != null)
            {
                foreach (EndpointInfo endpoint in endpoints.OrderBy(e => e.RoutePattern).ThenBy(e => e.HttpMethods))
                {
                    this.WriteEndpoint("..", endpoint);
                }
            }
        }

        /// <summary>
        /// Writes the specified endpoint to the console.
        /// </summary>
        /// <param name="spacing">The spacing.</param>
        /// <param name="endpoint">The endpoint.</param>
        protected virtual void WriteEndpoint(string spacing, EndpointInfo endpoint)
        {
            ConsoleHelper.WriteInformationLine(spacing + "Endpoint:");
            ConsoleHelper.WriteInformationLine(spacing + "..HttpMethods...: {0}", endpoint.HttpMethods);
            ConsoleHelper.WriteInformationLine(spacing + "..RoutePattern..: {0}", endpoint.RoutePattern);
            ConsoleHelper.WriteInformationLine(spacing + "..EndpointName..: {0}", endpoint.EndpointName);
            ConsoleHelper.WriteInformationLine(spacing + "..RouteName.....: {0}", endpoint.RouteName);
            ConsoleHelper.WriteInformationLine(spacing + "..ControllerName: {0}", endpoint.ControllerName);
            ConsoleHelper.WriteInformationLine(spacing + "..ActionName....: {0}", endpoint.ActionName);
            ConsoleHelper.WriteInformationLine(spacing + "..Order.........: {0}", endpoint.Order);
            ConsoleHelper.WriteInformationLine(spacing + "..DisplayName...: {0}", endpoint.DisplayName);
            ConsoleHelper.WriteInformationLine(spacing + "..ApiVersions...: {0}", endpoint.ApiVersions);
            ConsoleHelper.WriteInformationLine(spacing + "..Secured.......: {0}", endpoint.Secured);
        }

        /// <summary>
        /// Writes the specified exception to the console.
        /// </summary>
        /// <param name="ex">The exception.</param>
        protected virtual void WriteException(Exception ex)
        {
            ConsoleHelper.WriteErrorLine("An error was raised. See bellow.");
            ConsoleHelper.WriteErrorLine(ex);
        }

        /// <summary>
        /// Writes the specified service exception to the console.
        /// </summary>
        /// <param name="ex">The exception.</param>
        /// <param name="writeTitle">A value indicating whether the title should be written.</param>
        protected virtual void WriteServiceException(ServiceException ex, bool writeTitle = true)
        {
            if (writeTitle)
            {
                ConsoleHelper.WriteErrorLine("Web API returned an error. See bellow.");
            }

            ConsoleHelper.WriteErrorLine(ex.Message);
            this.WriteServiceExceptionError(string.Empty, ex.Body);
            this.WriteServiceExceptionRequest(ex.Request);
            this.WriteServiceExceptionResponse(ex.Response);

            ServiceException innerServiceException = ex.InnerException as ServiceException;
            if (innerServiceException != null)
            {
                this.WriteServiceException(innerServiceException, false);
            }
            else
            {
                this.WriteServiceExceptionInner(ex.InnerException);
            }
        }

        /// <summary>
        /// Writes the specified service error to the console.
        /// </summary>
        /// <param name="spacing">The spacing.</param>
        /// <param name="error">The service error.</param>
        protected virtual void WriteServiceExceptionError(string spacing, ServiceError error)
        {
            if (error != null)
            {
                ConsoleHelper.WriteErrorLine(spacing + "Error code...: '{0}'", error.Code);
                ConsoleHelper.WriteErrorLine(spacing + "Error message: '{0}'", error.Message);
                if (error.Details != null)
                {
                    foreach (ServiceErrorDetail detail in error.Details)
                    {
                        this.WriteServiceExceptionErrorDetail(spacing + "..", detail);
                    }
                }
            }
        }

        /// <summary>
        /// Writes the specified service error detail to the console.
        /// </summary>
        /// <param name="spacing">The spacing.</param>
        /// <param name="error">The service error detail.</param>
        protected virtual void WriteServiceExceptionErrorDetail(string spacing, ServiceErrorDetail error)
        {
            if (error != null)
            {
                ConsoleHelper.WriteErrorLine(spacing + "Error code...: '{0}'", error.Code);
                ConsoleHelper.WriteErrorLine(spacing + "Error message: '{0}'", error.Message);
            }
        }

        /// <summary>
        /// Writes the specified request message to the console.
        /// </summary>
        /// <param name="request">The request message.</param>
        protected virtual void WriteServiceExceptionRequest(HttpRequestMessageSurrogate request)
        {
            if (request != null)
            {
                ConsoleHelper.WriteErrorLine("Request:");
                ConsoleHelper.WriteErrorLine("..URI...: '{0}'", request.RequestUri.AbsoluteUri);
                ConsoleHelper.WriteErrorLine("..Method: '{0}'", request.Method.Method);
                this.WriteHeaders(request.Headers);
            }
        }

        /// <summary>
        /// Writes the specified response message to the console.
        /// </summary>
        /// <param name="response">The response message.</param>
        protected virtual void WriteServiceExceptionResponse(HttpResponseMessageSurrogate response)
        {
            if (response != null)
            {
                ConsoleHelper.WriteErrorLine("Response:");
                ConsoleHelper.WriteErrorLine("..StatusCode..: '{0}'", response.StatusCode);
                ConsoleHelper.WriteErrorLine("..ReasonPhrase: '{0}'", response.ReasonPhrase);
                this.WriteHeaders(response.Headers);
            }
        }

        /// <summary>
        /// Writes the specified inner exception to the console.
        /// </summary>
        /// <param name="ex">The exception.</param>
        protected virtual void WriteServiceExceptionInner(Exception ex)
        {
            if (ex != null)
            {
                ConsoleHelper.WriteErrorLine("Inner Exception:");
                ConsoleHelper.WriteErrorLine("..Message: '{0}'", ex.Message);
            }
        }

        /// <summary>
        /// Writes the specified headers to the console.
        /// </summary>
        /// <param name="headers">The headers.</param>
        protected virtual void WriteHeaders(IReadOnlyDictionary<string, IEnumerable<string>> headers)
        {
            if (headers != null)
            {
                ConsoleHelper.WriteErrorLine("..Headers:");

                foreach (string key in headers.Keys)
                {
                    ConsoleHelper.WriteErrorLine("....Header '{0}'", key);

                    foreach (string value in headers[key])
                    {
                        ConsoleHelper.WriteErrorLine("......'{0}'", value);
                    }
                }
            }
        }

        /// <summary>
        /// Checks the configuration.
        /// </summary>
        protected virtual bool CheckConfiguration()
        {
            if (this.Configuration.Environments == null)
            {
                ConsoleHelper.WriteErrorLine("The environments are missing in configuration.");
                ConsoleHelper.WriteErrorLine("Please press any key to quit.");
                ConsoleHelper.ReadKey();
                return false;
            }

            if (string.IsNullOrEmpty(this.Configuration.Environments.LocalServiceBaseUri) &&
                string.IsNullOrEmpty(this.Configuration.Environments.DevelopmentServiceBaseUri) &&
                string.IsNullOrEmpty(this.Configuration.Environments.StagingServiceBaseUri) &&
                string.IsNullOrEmpty(this.Configuration.Environments.PreviewServiceBaseUri) &&
                string.IsNullOrEmpty(this.Configuration.Environments.ProductionServiceBaseUri))
            {
                ConsoleHelper.WriteErrorLine("You need to the specify the address of at least one environment in configuration.");
                ConsoleHelper.WriteErrorLine("Please press any key to quit.");
                ConsoleHelper.ReadKey();
                return false;
            }

            return true;
        }

        /// <summary>
        /// Selects the active environment.
        /// </summary>
        protected virtual void SelectEnvironment()
        {
            bool hasLocalDevelopment = !string.IsNullOrEmpty(this.Configuration.Environments.LocalServiceBaseUri);
            bool hasDevelopment = !string.IsNullOrEmpty(this.Configuration.Environments.DevelopmentServiceBaseUri);
            bool hasStaging = !string.IsNullOrEmpty(this.Configuration.Environments.StagingServiceBaseUri);
            bool hasPreview = !string.IsNullOrEmpty(this.Configuration.Environments.PreviewServiceBaseUri);
            bool hasProduction = !string.IsNullOrEmpty(this.Configuration.Environments.ProductionServiceBaseUri);

            List<string> selectors = new List<string>();

            if (hasLocalDevelopment)
            {
                selectors.Add("1 = Local");
            }

            if (hasDevelopment)
            {
                selectors.Add("2 = Development");
            }

            if (hasStaging)
            {
                selectors.Add("3 = Staging");
            }

            if (hasPreview)
            {
                selectors.Add("4 = Preview");
            }

            if (hasProduction)
            {
                selectors.Add("5 = Production");
            }

            ConsoleHelper.WriteLine();
            ConsoleHelper.Write($"Please select the environment ({string.Join(", ", selectors)}): ");
            ConsoleKeyInfo keyEnv = ConsoleHelper.ReadKey();
            ConsoleHelper.WriteLine();

            switch (keyEnv.Key)
            {
                case ConsoleKey.D2:
                case ConsoleKey.NumPad2:
                    this.Configuration.ServiceBaseUri = this.Configuration.Environments.DevelopmentServiceBaseUri;
                    break;
                case ConsoleKey.D3:
                case ConsoleKey.NumPad3:
                    this.Configuration.ServiceBaseUri = this.Configuration.Environments.StagingServiceBaseUri;
                    break;
                case ConsoleKey.D4:
                case ConsoleKey.NumPad4:
                    this.Configuration.ServiceBaseUri = this.Configuration.Environments.PreviewServiceBaseUri;
                    break;
                case ConsoleKey.D5:
                case ConsoleKey.NumPad5:
                    this.Configuration.ServiceBaseUri = this.Configuration.Environments.ProductionServiceBaseUri;
                    break;
                default:
                    if (hasLocalDevelopment)
                    {
                        this.Configuration.ServiceBaseUri = this.Configuration.Environments.LocalServiceBaseUri;
                    }
                    else if (hasDevelopment)
                    {
                        this.Configuration.ServiceBaseUri = this.Configuration.Environments.DevelopmentServiceBaseUri;
                    }
                    else if (hasStaging)
                    {
                        this.Configuration.ServiceBaseUri = this.Configuration.Environments.StagingServiceBaseUri;
                    }
                    else if (hasPreview)
                    {
                        this.Configuration.ServiceBaseUri = this.Configuration.Environments.PreviewServiceBaseUri;
                    }
                    else
                    {
                        this.Configuration.ServiceBaseUri = this.Configuration.Environments.ProductionServiceBaseUri;
                    }

                    break;
            }

            ConsoleHelper.WriteLine();

            this.DisposeServiceClient();
        }

        /// <summary>
        /// Writes the additional configuration.
        /// </summary>
        protected virtual void WriteAdditionalConfiguration()
        {
        }

        /// <summary>
        /// Writes the configuration.
        /// </summary>
        protected virtual void WriteConfiguration()
        {
            ConsoleHelper.WriteLine("=======================================");
            ConsoleHelper.WriteLine("Service: {0}", this.Configuration.ServiceBaseUri);
            ConsoleHelper.WriteLine("Client Id: {0}", Constants.ClientId);
            this.WriteAdditionalConfiguration();
            ConsoleHelper.WriteLine("=======================================");
        }

        /// <summary>
        /// Shows the monitoring menu.
        /// </summary>
        /// <returns>
        /// A value indicating whether the user chose to quit the application.
        /// </returns>
        protected virtual async Task<bool> ShowMonitoringMenuAsync()
        {
            // Menu

            bool terminate = false;
            bool cont = true;
            while (cont)
            {
                ConsoleHelper.WriteLine();
                ConsoleHelper.WriteLine("========================================");
                ConsoleHelper.WriteLine("Monitoring Menu");
                this.WriteConfiguration();
                ConsoleHelper.WriteLine();
                ConsoleHelper.WriteLine("1. Probe.");
                ConsoleHelper.WriteLine("2. Diagnostics.");
                ConsoleHelper.WriteLine("3. Endpoints.");
                ConsoleHelper.WriteLine("4. Configuration.");
                ConsoleHelper.WriteLine("<. Back.");
                ConsoleHelper.WriteLine("Q. Quit.");
                ConsoleHelper.Write(">> ");

                ConsoleKeyInfo key = ConsoleHelper.ReadKey();
                ConsoleHelper.WriteLine();

                switch (key.Key)
                {
                    case ConsoleKey.Q:
                        cont = false;
                        terminate = true;
                        break;
                    case ConsoleKey.LeftArrow:
                        cont = false;
                        break;
                    case ConsoleKey.D1:
                    case ConsoleKey.NumPad1:
                        await this.ProbeAsync().ConfigureAwait(false);
                        break;
                    case ConsoleKey.D2:
                    case ConsoleKey.NumPad2:
                        await this.DiagnosticsAsync().ConfigureAwait(false);
                        break;
                    case ConsoleKey.D3:
                    case ConsoleKey.NumPad3:
                        await this.EndpointsAsync().ConfigureAwait(false);
                        break;
                    case ConsoleKey.D4:
                    case ConsoleKey.NumPad4:
                        await this.ConfigurationAsync().ConfigureAwait(false);
                        break;
                    default:
                        break;
                }
            }

            // Result

            return terminate;
        }

        /// <summary>
        /// Executes the probe endpoint.
        /// </summary>
        /// <returns>
        /// The <see cref="Task"/> that represents the asynchronous operation.
        /// </returns>
        protected virtual async Task ProbeAsync()
        {
            // Call the Web API

            ConsoleHelper.WriteLine();
            ConsoleHelper.WriteInformationLine("Calling the Web API...");

            try
            {
                ServiceOperationResult<string> response = await this.Client.Monitoring.ProbeAsync().ConfigureAwait(false);

                ConsoleHelper.WriteInformationLine("Web API call succeeded. Result: {0}.", response.Body);
            }
            catch (ServiceException ex)
            {
                this.WriteServiceException(ex);
            }
            catch (Exception ex)
            {
                ConsoleHelper.WriteErrorLine(ex);
            }
        }

        /// <summary>
        /// Executes the diagnosis endpoint.
        /// </summary>
        /// <returns>
        /// The <see cref="Task"/> that represents the asynchronous operation.
        /// </returns>
        protected virtual async Task DiagnosticsAsync()
        {
            // Call the Web API

            ConsoleHelper.WriteLine();
            ConsoleHelper.WriteInformationLine("Calling the Web API...");

            try
            {
                ServiceOperationResult<string> response = await this.Client.Monitoring.DiagnosticsAsync().ConfigureAwait(false);

                ConsoleHelper.WriteInformationLine("Web API call succeeded. Result: {0}.", response.Body);
            }
            catch (ServiceException ex)
            {
                this.WriteServiceException(ex);
            }
            catch (Exception ex)
            {
                ConsoleHelper.WriteErrorLine(ex);
            }
        }

        /// <summary>
        /// Executes the endpoints analyzer endpoint.
        /// </summary>
        /// <returns>
        /// The <see cref="Task"/> that represents the asynchronous operation.
        /// </returns>
        protected virtual async Task EndpointsAsync()
        {
            // Call the Web API

            ConsoleHelper.WriteLine();
            ConsoleHelper.WriteInformationLine("Calling the Web API...");

            try
            {
                ServiceOperationResult<IEnumerable<EndpointInfo>> response = await this.Client.Monitoring.EndpointsAsync().ConfigureAwait(false);

                ConsoleHelper.WriteInformationLine("Web API returned the result. See below.");

                IEnumerable<EndpointInfo> endpoints = response.Body;

                WriteEndpoints(endpoints);
            }
            catch (ServiceException ex)
            {
                this.WriteServiceException(ex);
            }
            catch (Exception ex)
            {
                ConsoleHelper.WriteErrorLine(ex);
            }
        }

        /// <summary>
        /// Executes the configuration analyzer endpoint.
        /// </summary>
        /// <returns>
        /// The <see cref="Task"/> that represents the asynchronous operation.
        /// </returns>
        protected virtual async Task ConfigurationAsync()
        {
            // Call the Web API

            ConsoleHelper.WriteLine();
            ConsoleHelper.WriteInformationLine("Calling the Web API...");

            try
            {
                ServiceOperationResult<string> response = await this.Client.Monitoring.ConfigurationAsync().ConfigureAwait(false);

                ConsoleHelper.WriteInformationLine("Web API call succeeded. Result: {0}.", response.Body);
            }
            catch (ServiceException ex)
            {
                this.WriteServiceException(ex);
            }
            catch (Exception ex)
            {
                ConsoleHelper.WriteErrorLine(ex);
            }
        }

        /// <summary>
        /// Gets a string value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The string value specified by the user.
        /// </returns>
        protected virtual string GetValueString(string name, string defaultValue = null)
        {
            return this.GetValueString(name, true, defaultValue);
        }

        /// <summary>
        /// Gets a string value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <param name="blankToStop">A value indicating whether a blank value equals stopping.</param>
        /// <returns>
        /// The string value specified by the user.
        /// </returns>
        protected virtual string GetValueString(string name, bool required, string defaultValue = null, bool blankToStop = false)
        {
            string value = defaultValue;

            bool cont = false;
            while (!cont)
            {
                if (required)
                {
                    if (string.IsNullOrEmpty(defaultValue))
                    {
                        ConsoleHelper.Write($"Please enter the {name}: ");
                    }
                    else
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                    }
                }
                else
                {
                    if (string.IsNullOrEmpty(defaultValue))
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = ignore): ");
                    }
                    else
                    {
                        if (blankToStop)
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank to stop): ");
                        }
                        else
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                        }
                    }
                }

                string valueStr = System.Console.ReadLine();
                if (!string.IsNullOrEmpty(valueStr))
                {
                    value = valueStr;
                }

                if (required)
                {
                    cont = !string.IsNullOrEmpty(value);
                }
                else
                {
                    cont = true;
                }
            }

            return value;
        }

        /// <summary>
        /// Gets a boolean value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The boolean value specified by the user.
        /// </returns>
        protected virtual bool GetValueBoolean(string name, bool? defaultValue = null)
        {
            return this.GetValueBoolean(name, true, defaultValue);
        }

        /// <summary>
        /// Gets a boolean value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <param name="blankToStop">A value indicating whether a blank value equals stopping.</param>
        /// <returns>
        /// The boolean value specified by the user.
        /// </returns>
        protected virtual bool GetValueBoolean(string name, bool required, bool? defaultValue = null, bool blankToStop = false)
        {
            bool? value = defaultValue;

            bool cont = false;
            while (!cont)
            {
                if (required)
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name} (y/n): ");
                    }
                    else
                    {
                        string defaultValueStr = defaultValue ?? false ? "y" : "n";
                        ConsoleHelper.Write($"Please enter the {name} (y/n) (blank = {defaultValueStr}): ");
                    }
                }
                else
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name} (y/n) (blank = ignore): ");
                    }
                    else
                    {
                        if (blankToStop)
                        {
                            ConsoleHelper.Write($"Please enter the {name} (y/n) (blank to stop): ");
                        }
                        else
                        {
                            string defaultValueStr = defaultValue ?? false ? "y" : "n";
                            ConsoleHelper.Write($"Please enter the {name} (y/n) (blank = {defaultValueStr}): ");
                        }
                    }
                }

                string valueStr = System.Console.ReadLine();
                if (!string.IsNullOrEmpty(valueStr))
                {
                    if (valueStr.EqualsNoCase("Y"))
                    {
                        value = true;
                    }
                    else if (valueStr.EqualsNoCase("N"))
                    {
                        value = false;
                    }
                    else
                    {
                        value = null;
                    }
                }

                if (required)
                {
                    cont = value != null;
                }
                else
                {
                    cont = true;
                }
            }

            return value.GetValueOrDefault();
        }

        /// <summary>
        /// Gets a integer value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The integer value specified by the user.
        /// </returns>
        protected virtual int GetValueInteger(string name, int? defaultValue = null)
        {
            return this.GetValueInteger(name, true, defaultValue).GetValueOrDefault();
        }

        /// <summary>
        /// Gets an integer value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <param name="blankToStop">A value indicating whether a blank value equals stopping.</param>
        /// <returns>
        /// The integer value specified by the user.
        /// </returns>
        protected virtual int? GetValueInteger(string name, bool required, int? defaultValue = null, bool blankToStop = false)
        {
            int? value = defaultValue;

            bool cont = false;
            while (!cont)
            {
                if (required)
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name}: ");
                    }
                    else
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                    }
                }
                else
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = ignore): ");
                    }
                    else
                    {
                        if (blankToStop)
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank to stop): ");
                        }
                        else
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                        }
                    }
                }

                string valueStr = System.Console.ReadLine();
                if (!string.IsNullOrEmpty(valueStr))
                {
                    if (int.TryParse(valueStr, out int valueInt))
                    {
                        value = valueInt;
                    }
                }

                if (required)
                {
                    cont = value != null;
                }
                else
                {
                    cont = true;
                }
            }

            return value;
        }

        /// <summary>
        /// Gets a long value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The long value specified by the user.
        /// </returns>
        protected virtual long GetValueLong(string name, long? defaultValue = null)
        {
            return this.GetValueLong(name, true, defaultValue);
        }

        /// <summary>
        /// Gets a long value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <param name="blankToStop">A value indicating whether a blank value equals stopping.</param>
        /// <returns>
        /// The long value specified by the user.
        /// </returns>
        protected virtual long GetValueLong(string name, bool required, long? defaultValue = null, bool blankToStop = false)
        {
            long? value = defaultValue;

            bool cont = false;
            while (!cont)
            {
                if (required)
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name}: ");
                    }
                    else
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                    }
                }
                else
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = ignore): ");
                    }
                    else
                    {
                        if (blankToStop)
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank to stop): ");
                        }
                        else
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                        }
                    }
                }

                string valueStr = System.Console.ReadLine();
                if (!string.IsNullOrEmpty(valueStr))
                {
                    if (long.TryParse(valueStr, out long valueLong))
                    {
                        value = valueLong;
                    }
                }

                if (required)
                {
                    cont = value != null;
                }
                else
                {
                    cont = true;
                }
            }

            return value.GetValueOrDefault();
        }

        /// <summary>
        /// Gets a double value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The double value specified by the user.
        /// </returns>
        protected virtual double GetValueDouble(string name, double? defaultValue = null)
        {
            return this.GetValueDouble(name, true, defaultValue);
        }

        /// <summary>
        /// Gets a double value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <param name="blankToStop">A value indicating whether a blank value equals stopping.</param>
        /// <returns>
        /// The double value specified by the user.
        /// </returns>
        protected virtual double GetValueDouble(string name, bool required, double? defaultValue = null, bool blankToStop = false)
        {
            double? value = defaultValue;

            bool cont = false;
            while (!cont)
            {
                if (required)
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name}: ");
                    }
                    else
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                    }
                }
                else
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = ignore): ");
                    }
                    else
                    {
                        if (blankToStop)
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank to stop): ");
                        }
                        else
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                        }
                    }
                }

                string valueStr = System.Console.ReadLine();
                if (!string.IsNullOrEmpty(valueStr))
                {
                    if (double.TryParse(valueStr, out double valueDouble))
                    {
                        value = valueDouble;
                    }
                }

                if (required)
                {
                    cont = value != null;
                }
                else
                {
                    cont = true;
                }
            }

            return value.GetValueOrDefault();
        }

        /// <summary>
        /// Gets a decimal value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The decimal value specified by the user.
        /// </returns>
        protected virtual decimal GetValueDecimal(string name, decimal? defaultValue = null)
        {
            return this.GetValueDecimal(name, true, defaultValue);
        }

        /// <summary>
        /// Gets a decimal value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <param name="blankToStop">A value indicating whether a blank value equals stopping.</param>
        /// <returns>
        /// The decimal value specified by the user.
        /// </returns>
        protected virtual decimal GetValueDecimal(string name, bool required, decimal? defaultValue = null, bool blankToStop = false)
        {
            decimal? value = defaultValue;

            bool cont = false;
            while (!cont)
            {
                if (required)
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name}: ");
                    }
                    else
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                    }
                }
                else
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = ignore): ");
                    }
                    else
                    {
                        if (blankToStop)
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank to stop): ");
                        }
                        else
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                        }
                    }
                }

                string valueStr = System.Console.ReadLine();
                if (!string.IsNullOrEmpty(valueStr))
                {
                    if (decimal.TryParse(valueStr, out decimal valueDecimal))
                    {
                        value = valueDecimal;
                    }
                }

                if (required)
                {
                    cont = value != null;
                }
                else
                {
                    cont = true;
                }
            }

            return value.GetValueOrDefault();
        }

        /// <summary>
        /// Gets a integer value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The URL value specified by the user.
        /// </returns>
        protected virtual Uri GetValueUri(string name, Uri defaultValue = null)
        {
            return this.GetValueUri(name, true, defaultValue);
        }

        /// <summary>
        /// Gets a URL value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <param name="blankToStop">A value indicating whether a blank value equals stopping.</param>
        /// <returns>
        /// The URL value specified by the user.
        /// </returns>
        protected virtual Uri GetValueUri(string name, bool required, Uri defaultValue = null, bool blankToStop = false)
        {
            Uri value = defaultValue;

            bool cont = false;
            while (!cont)
            {
                if (required)
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name}: ");
                    }
                    else
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                    }
                }
                else
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = ignore): ");
                    }
                    else
                    {
                        if (blankToStop)
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank to stop): ");
                        }
                        else
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                        }
                    }
                }

                string valueStr = System.Console.ReadLine();
                if (!string.IsNullOrEmpty(valueStr))
                {
                    if (Uri.TryCreate(valueStr, UriKind.Absolute, out Uri valueUri))
                    {
                        value = valueUri;
                    }
                }

                if (required)
                {
                    cont = value != null;
                }
                else
                {
                    cont = true;
                }
            }

            return value;
        }

        /// <summary>
        /// Gets a date time value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The date time value specified by the user.
        /// </returns>
        protected virtual DateTime GetValueDateTime(string name, DateTime? defaultValue = null)
        {
            return this.GetValueDateTime(name, true, defaultValue);
        }

        /// <summary>
        /// Gets an date time value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <param name="blankToStop">A value indicating whether a blank value equals stopping.</param>
        /// <returns>
        /// The date time value specified by the user.
        /// </returns>
        protected virtual DateTime GetValueDateTime(string name, bool required, DateTime? defaultValue = null, bool blankToStop = false)
        {
            DateTime? value = defaultValue;

            bool cont = false;
            while (!cont)
            {
                if (required)
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name}: ");
                    }
                    else
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                    }
                }
                else
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = ignore): ");
                    }
                    else
                    {
                        if (blankToStop)
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank to stop): ");
                        }
                        else
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                        }
                    }
                }

                string valueStr = System.Console.ReadLine();
                if (!string.IsNullOrEmpty(valueStr))
                {
                    if (DateTime.TryParse(valueStr, out DateTime valueDateTime))
                    {
                        value = valueDateTime;
                    }
                }

                if (required)
                {
                    cont = value != null;
                }
                else
                {
                    cont = true;
                }
            }

            return value.GetValueOrDefault();
        }

        /// <summary>
        /// Gets a unique identifier value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The unique identifier value specified by the user.
        /// </returns>
        protected virtual Guid GetValueGuid(string name, Guid? defaultValue = null)
        {
            return this.GetValueGuid(name, true, defaultValue);
        }

        /// <summary>
        /// Gets a unique identifier value from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <param name="blankToStop">A value indicating whether a blank value equals stopping.</param>
        /// <returns>
        /// The unique identifier value specified by the user.
        /// </returns>
        protected virtual Guid GetValueGuid(string name, bool required, Guid? defaultValue = null, bool blankToStop = false)
        {
            Guid? value = defaultValue;

            bool cont = false;
            while (!cont)
            {
                if (required)
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name}: ");
                    }
                    else
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                    }
                }
                else
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = ignore): ");
                    }
                    else
                    {
                        if (blankToStop)
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank to stop): ");
                        }
                        else
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                        }
                    }
                }

                string valueStr = System.Console.ReadLine();
                if (!string.IsNullOrEmpty(valueStr))
                {
                    if (Guid.TryParse(valueStr, out Guid valueGuid))
                    {
                        value = valueGuid;
                    }
                }

                if (required)
                {
                    cont = value != null;
                }
                else
                {
                    cont = true;
                }
            }

            return value.GetValueOrDefault();
        }

        /// <summary>
        /// Gets an enumeration value from user input.
        /// </summary>
        /// <typeparam name="TEnum">The type of the enumeration.</typeparam>
        /// <param name="name">The value name.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The enumeration value specified by the user.
        /// </returns>
        protected virtual TEnum GetValueEnum<TEnum>(string name, TEnum? defaultValue = null)
            where TEnum : struct
        {
            return this.GetValueEnum(name, true, defaultValue);
        }

        /// <summary>
        /// Gets an enumeration value from user input.
        /// </summary>
        /// <typeparam name="TEnum">The type of the enumeration.</typeparam>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <param name="blankToStop">A value indicating whether a blank value equals stopping.</param>
        /// <returns>
        /// The enumeration value specified by the user.
        /// </returns>
        protected virtual TEnum GetValueEnum<TEnum>(string name, bool required, TEnum? defaultValue = null, bool blankToStop = false)
            where TEnum : struct
        {
            TEnum? value = defaultValue;

            bool cont = false;
            while (!cont)
            {
                if (required)
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name}: ");
                    }
                    else
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                    }
                }
                else
                {
                    if (defaultValue == null)
                    {
                        ConsoleHelper.Write($"Please enter the {name} (blank = ignore): ");
                    }
                    else
                    {
                        if (blankToStop)
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank to stop): ");
                        }
                        else
                        {
                            ConsoleHelper.Write($"Please enter the {name} (blank = {defaultValue}): ");
                        }
                    }
                }

                string valueStr = System.Console.ReadLine();
                if (!string.IsNullOrEmpty(valueStr))
                {
                    if (Enum.TryParse(valueStr, true, out TEnum valueEnum))
                    {
                        value = valueEnum;
                    }
                }

                if (required)
                {
                    cont = value != null;
                }
                else
                {
                    cont = true;
                }
            }

            return value.GetValueOrDefault();
        }

        /// <summary>
        /// Gets a list of string values from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The list of string values specified by the user.
        /// </returns>
        protected virtual IEnumerable<string> GetValuesString(string name, bool required, string defaultValue = null)
        {
            List<string> result = new List<string>();

            bool stop = false;
            bool first = true;

            while (!stop)
            {
                string value = this.GetValueString(name, required && first, first ? defaultValue : null, true);

                if (!string.IsNullOrEmpty(value))
                {
                    result.Add(value);
                }
                else
                {
                    stop = true;
                }

                first = false;
            }

            return result;
        }

        /// <summary>
        /// Gets a list of int values from user input.
        /// </summary>
        /// <param name="name">The value name.</param>
        /// <param name="required">A value indicating whether the value is required.</param>
        /// <param name="defaultValue">The default value.</param>
        /// <returns>
        /// The list of int values specified by the user.
        /// </returns>
        protected virtual IEnumerable<int> GetValuesInteger(string name, bool required, int? defaultValue = null)
        {
            List<int> result = new List<int>();

            bool stop = false;
            bool first = true;

            while (!stop)
            {
                int? value = this.GetValueInteger(name, required && first, first ? defaultValue : null, true);

                if (value != null)
                {
                    result.Add(value.Value);
                }
                else
                {
                    stop = true;
                }

                first = false;
            }

            return result;
        }

        /// <summary>
        /// Gets a dictionary of string values from user input.
        /// </summary>
        /// <param name="keyName">The key name.</param>
        /// <param name="valueName">The value name.</param>
        /// <param name="notEmpty">A value indicating whether the result is required to be not empty.</param>
        /// <param name="valueRequired">A value indicating whether the value for each dictionary item is required.</param>
        /// <returns>
        /// The dictionary of string values specified by the user.
        /// </returns>
        protected virtual IDictionary<string, string> GetDictionaryString(string keyName, string valueName, bool notEmpty, bool valueRequired)
        {
            Dictionary<string, string> result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            bool stop = false;
            bool first = true;

            while (!stop)
            {
                string key = this.GetValueString(keyName, notEmpty && first, null, first ? !notEmpty : true);

                if (!string.IsNullOrEmpty(key))
                {
                    string value = this.GetValueString(valueName, valueRequired);

                    if (result.ContainsKey(key))
                    {
                        result[key] = value;
                    }
                    else
                    {
                        result.Add(key, value);
                    }
                }
                else
                {
                    stop = true;
                }

                first = false;
            }

            return result;
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Defines the type that implements the application.
    /// </summary>
    /// <seealso cref="ApplicationBase" />
    [GeneratedCode("Lithium", "2.0")]
    [SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Justification = "Created via dependency injection.")]
    internal sealed partial class Application : ApplicationBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="Application"/> class.
        /// </summary>
        /// <param name="options">The application configuration options.</param>
        public Application(ApplicationConfiguration options)        
            : base(options)
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
