//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Primavera.Lithium.PythonConnector.Client.Console
{
    #region Code

    #region Internal Classes

    /// <summary>
    /// Defines constants used by the application.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    internal static partial class Constants
    {
        #region Code

        #region Internal Constants

        /// <summary>
        /// The client identifier.
        /// </summary>
        internal const string ClientId = "lithium-pythonconnector-clientcredentials";

        /// <summary>
        /// The client secret.
        /// </summary>
        internal const string ClientSecret = "fsessbfbdfbndgnfgnhj";

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
