//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Threading.Tasks;

namespace Primavera.Lithium.PythonConnector.Client.Console
{
    #region Code

    #region Internal Interfaces

    /// <summary>
    /// Defines the interface of the type that implements the application.
    /// </summary>
    /// <seealso cref="IDisposable" />
    [GeneratedCode("Lithium", "2.0")]
    internal partial interface IApplication : IDisposable
    {
        #region Code

        #region Methods

        /// <summary>
        /// Runs the application.
        /// </summary>
        /// <returns>
        /// The <see cref="Task"/> that represents the asynchronous operation.
        /// </returns>
        Task RunAsync();

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
